create tag if github pushes to master

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -2,7 +2,8 @@ name: Go
 
 on:
   push:
-    branches: [ master ]
+    branches:
+      - '**'
   pull_request:
     branches: [ master ]
 
@@ -12,10 +13,6 @@ jobs:
     name: Build
     runs-on: ubuntu-latest
     steps:
-
-    - name: Debug
-      run: |
-        cat ${GITHUB_EVENT_PATH}
 
     - name: Set up Go 1.x
       uses: actions/setup-go@v2
@@ -52,7 +49,7 @@ jobs:
 
   release:
     needs: build
-    if: github.event.pull_request.merged == true
+    if: github.event.head_commit.committer.name == 'GitHub' && github.event.ref == 'refs/heads/master'
     name: Release
     runs-on: ubuntu-latest
     steps:
@@ -69,12 +66,11 @@ jobs:
 
     - name: Create new tag
       run: |
-        git fetch --tags
+        set -x
+        git fetch --tags || echo "could not fetch tags"
         latest_version=$(git describe --tags --match "[0-9]*.[0-9]*.[0-9]*" --abbrev=0)
-        version_array=( ${latest_version//./ } )
-        ((version_array[1]++))
-        version_array[2]=0
-        new_version="${version_array[0]}.${version_array[1]}.${version_array[2]}"
+
+        new_version=$(python3 .github/scripts/version.py ${latest_version} --minor)
 
         git config --global user.email "mdreem@fastmail.fm"
         git config --global user.name "Github Action"
